/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2025-04-20 13:27:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.PostManagement;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PostManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1725271156711L));
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>Post Management | Admin Dashboard</title>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./PostManagement.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../index.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./profile.css\"/>\r\n");
      out.write("\r\n");
      out.write("  <!-- icons -->\r\n");
      out.write("  <link\r\n");
      out.write("          rel=\"stylesheet\"\r\n");
      out.write("          data-purpose=\"Layout StyleSheet\"\r\n");
      out.write("          title=\"Web Awesome\"\r\n");
      out.write("          href=\"/css/app-wa-09b459cf485d4b1f3304947240314c05.css?vsn=d\"\r\n");
      out.write("  />\r\n");
      out.write("\r\n");
      out.write("  <link\r\n");
      out.write("          rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/all.css\"\r\n");
      out.write("  />\r\n");
      out.write("\r\n");
      out.write("  <link\r\n");
      out.write("          rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-duotone-solid.css\"\r\n");
      out.write("  />\r\n");
      out.write("\r\n");
      out.write("  <link\r\n");
      out.write("          rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-thin.css\"\r\n");
      out.write("  />\r\n");
      out.write("\r\n");
      out.write("  <link\r\n");
      out.write("          rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-solid.css\"\r\n");
      out.write("  />\r\n");
      out.write("\r\n");
      out.write("  <link\r\n");
      out.write("          rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-regular.css\"\r\n");
      out.write("  />\r\n");
      out.write("  <link\r\n");
      out.write("          rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/solid.css\"\r\n");
      out.write("  />\r\n");
      out.write("  <link\r\n");
      out.write("          rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-light.css\"\r\n");
      out.write("  />\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("<div class=\"navMenu f-col center\">\r\n");
      out.write("  <div class=\"logo\">\r\n");
      out.write("    <img src=\"../assets/logo.png\" alt=\"Parlimate\" id=\"logo\" />\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"navigation\">\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"../Home/index.jsp\" class=\"nav-item f-row\">\r\n");
      out.write("          <i class=\"fa-regular fa-house\"></i>\r\n");
      out.write("          <span>home</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/userManagement/UserManagementServlet\" class=\"nav-item f-row \">\r\n");
      out.write("          <i class=\"fa-regular fa-users\"></i>\r\n");
      out.write("          <span>user management</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/Fundraising/FundraisingManagementServlet\" class=\"nav-item f-row\">\r\n");
      out.write("          <i class=\"fa-regular fa-briefcase\"></i>\r\n");
      out.write("          <span>fundraise management</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"#\" class=\"nav-item f-row\">\r\n");
      out.write("          <i class=\"fa-regular fa-check-to-slot\"></i>\r\n");
      out.write("          <span>survey management</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/PostManagement/PostManagementServlet\" class=\"nav-item f-row active\">\r\n");
      out.write("          <i class=\"fa-regular fa-cards-blank\"></i>\r\n");
      out.write("          <span>post management</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/CommentManagement/CommentManagementServlet\" class=\"nav-item f-row \">\r\n");
      out.write("          <i class=\"fa-regular fa-comments\"></i>\r\n");
      out.write("          <span>Comment Management</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"#\" class=\"nav-item f-row\">\r\n");
      out.write("          <i class=\"fa-regular fa-circle-check\"></i>\r\n");
      out.write("          <span>requests</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/BankTransferManagement/BankTransferManagementServlet\" class=\"nav-item f-row\">\r\n");
      out.write("          <i class=\"fa-regular fa-money-bill-transfer\"></i>\r\n");
      out.write("          <span>bank transfer management</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"#\" class=\"nav-item f-row\">\r\n");
      out.write("          <i class=\"fa-regular fa-sliders-up\"></i>\r\n");
      out.write("          <span>platform settings</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"#\" class=\"f-row profile\">\r\n");
      out.write("          <div class=\"p-img\"></div>\r\n");
      out.write("          <div class=\"sUser f-col\">\r\n");
      out.write("            <div class=\"name\">Naleeka Kumarasinghe</div>\r\n");
      out.write("            <div class=\"role\">Admin</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"#\" class=\"f-row log-out\">\r\n");
      out.write("          <i class=\"fa-solid fa-right-from-bracket\"></i>\r\n");
      out.write("          log out\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pageContent\">\r\n");
      out.write("  <div class=\"container f-col\">\r\n");
      out.write("    <div class=\"top f-row\">\r\n");
      out.write("      <div class=\"page f-col\">\r\n");
      out.write("        <div class=\"page-title capitalize\">Post management</div>\r\n");
      out.write("        <div class=\"page-desc\">\r\n");
      out.write("          Manage user posts\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"data f-col\">\r\n");
      out.write("      <table class=\"users\">\r\n");
      out.write("        <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>Post ID</td>\r\n");
      out.write("          <td>User ID</td>\r\n");
      out.write("          <td>User name </td>\r\n");
      out.write("          <td>Post content</td>\r\n");
      out.write("          <td class=\"head-row f-row\">posted on</td>\r\n");
      out.write("          <td>Delete Post</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /admin/PostManagement/PostManagement.jsp(169,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("post");
    // /admin/PostManagement/PostManagement.jsp(169,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin/PostManagement/PostManagement.jsp(169,8) '${alladminPosts}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${alladminPosts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          <tr>\r\n");
          out.write("            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.postId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("            <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.datetime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\r\n");
          out.write("            <td class=\"actbtn\">\r\n");
          out.write("\r\n");
          out.write("              <li class=\"f-row del-comment\">\r\n");
          out.write("                <i class=\"fa-regular fa-trash\"></i>\r\n");
          out.write("\r\n");
          out.write("                <form action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/PostManagement/DeleteAdminPostServlet\"\r\n");
          out.write("                      method=\"POST\"\r\n");
          out.write("                      onsubmit=\"return confirm('Are you sure you want to delete this post?');\"\r\n");
          out.write("                      style=\"display:inline;\">\r\n");
          out.write("                  <input type=\"hidden\" name=\"postId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.postId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\r\n");
          out.write("\r\n");
          out.write("                  <button type=\"submit\" class=\"delete-btn\">Delete</button>\r\n");
          out.write("                </form>\r\n");
          out.write("              </li>\r\n");
          out.write("              </ul>\r\n");
          out.write("            </td>\r\n");
          out.write("          </tr>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager());
    return false;
  }
}
