/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2025-04-07 02:07:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1725271156711L));
    _jspx_dependants.put("/index/sidebar.jsp", Long.valueOf(1743982942460L));
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/index/header/header.jsp", Long.valueOf(1738291078541L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
HttpSession session1 = request.getSession(false); // false to not create a new session if one doesn't exist
if (session1 == null || session.getAttribute("user") == null) {
// User is not logged in, redirect to login page
response.sendRedirect("index.jsp");
return;
}
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("  <title>Home | Parlimate</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"index/sidebar1.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"index/header/header.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"container.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"popup.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"comment.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"index.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"edit.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"fund-popup.css\"/>.\n");
      out.write("\n");
      out.write("  <!-- icons -->\n");
      out.write("  <link rel=\"stylesheet\" data-purpose=\"Layout StyleSheet\" title=\"Web Awesome\"\n");
      out.write("        href=\"/css/app-wa-09b459cf485d4b1f3304947240314c05.css?vsn=d\" />\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/all.css\" />\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-duotone-solid.css\" />\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-thin.css\" />\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-solid.css\" />\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-regular.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-light.css\" />\n");
      out.write("\n");
      out.write("  <style>\n");
      out.write("    .logo-img{\n");
      out.write("      height: 1.3rem;\n");
      out.write("      margin-bottom: -0.25rem;\n");
      out.write("    }\n");
      out.write("    .container{\n");
      out.write("      margin-top: 2.5rem;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"\">\n");
      out.write("\n");
      out.write("<form action=\"CreateRequestServlet\" method=\"post\" class=\"popup-f\" id=\"popup-f\" enctype=\"multipart/form-data\">\n");
      out.write("  <div class=\"bg\"></div>\n");
      out.write("  <div class=\"fund-popup col\">\n");
      out.write("    <div class=\"head row\">\n");
      out.write("      <div class=\"close-btn\">\n");
      out.write("        <i class=\"fa-solid fa-xmark\"></i>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"icon\">\n");
      out.write("        <i class=\"fa-regular fa-briefcase\"></i>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"title\">Request a fundraise</div>\n");
      out.write("      <div class=\"separator\"></div>\n");
      out.write("    </div>\n");
      out.write("    <input type=\"hidden\" name=\"userid\" id=\"useri\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("    <input type=\"hidden\" name=\"username\" id=\"usernam\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfile.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("    <div class=\"body col\">\n");
      out.write("      <div class=\"fund-title field\">\n");
      out.write("        <label for=\"fundtitle\" class=\"title\">Title</label>\n");
      out.write("        <input type=\"text\" required placeholder=\"Fundraise for the senior care house\" name=\"title\" id=\"fundtitle\">\n");
      out.write("      </div>\n");
      out.write("      <div class=\"fund-decs field\">\n");
      out.write("        <label for=\"fund-desc\" class=\"title\">Description</label>\n");
      out.write("        <textarea required name=\"description\" placeholder=\"Every elderly person deserves a life filled with dignity, care, and comfort...\" id=\"fund-desc\"></textarea>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"multi-fields row\">\n");
      out.write("        <div class=\"fund-cat field\">\n");
      out.write("          <label for=\"fund-categ\" class=\"title\">Category</label>\n");
      out.write("          <select required name=\"category\" id=\"fund-categ\">\n");
      out.write("            <option value=\"educational\">Educational</option>\n");
      out.write("            <option value=\"social\">Social</option>\n");
      out.write("            <option value=\"community-se\">Community Service</option>\n");
      out.write("          </select>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"fund-amount field col\">\n");
      out.write("          <label class=\"title\" for=\"fund-amount\">Fund Target</label>\n");
      out.write("          <div class=\"content row\">\n");
      out.write("            <div class=\"curr\">\n");
      out.write("              <select required name=\"currency\" id=\"fund-currency\">\n");
      out.write("                <option value=\"lkr\">LKR</option>\n");
      out.write("                <option value=\"usd\">USD</option>\n");
      out.write("              </select>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"amount\">\n");
      out.write("              <input required step=\"1000\" type=\"number\" name=\"targetamount\" id=\"fund-amount\" placeholder=\"1,000,000.00\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"fund-attach field\">\n");
      out.write("        <span for=\"\" class=\"title\">Upload Attachments</span>\n");
      out.write("        <div class=\"att-container\">\n");
      out.write("          <div class=\"action row\">\n");
      out.write("            <label for=\"fund-att\" class=\"att-btn\">Select File</label>\n");
      out.write("            <input type=\"file\" name=\"attachmentUrl\" id=\"fund-att\" multiple>\n");
      out.write("            <div class=\"sep\"></div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"att-content\">\n");
      out.write("            <span class=\"no-of-files\">No file attached</span>\n");
      out.write("            <ul id=\"att-list\" class=\"col\">\n");
      out.write("              <!-- uploaded files will be listed here -->\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"bottom row\">\n");
      out.write("      <button class=\"cancel-btn form-btn\">Cancel</button>\n");
      out.write("      <button type=\"submit\" class=\"submit-btn form-btn row\">\n");
      out.write("        <i class=\"fa-duotone fa-solid fa-check\"></i>\n");
      out.write("        Publish\n");
      out.write("      </button>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</form>\n");
      out.write("<div class=\"notification-msg capitalize\"></div>\n");
      out.write("<div class=\"popup-modal\">\n");
      out.write("  <div class=\"popup\">\n");
      out.write("    <div class=\"title\">\n");
      out.write("      New Post\n");
      out.write("      <div class=\"close-btn btn\" id=\"popup-close-btn\">\n");
      out.write("        <i class=\"fa-solid fa-times\"></i>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"breakLine\"></div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"content\">\n");
      out.write("      <div class=\"account row\">\n");
      out.write("        <div class=\"user-profile\">\n");
      out.write("          <div class=\"prof-img\"></div>\n");
      out.write("          <div class=\"user-name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfile.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"switch-btn capitalize\">\n");
      out.write("          <a href=\"#\">switch account\n");
      out.write("            <i class=\"fa-regular fa-chevron-down\"></i></a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <form method=\"POST\" action=\"PublishPostServlet\">\n");
      out.write("        <div class=\"caption-box col content-pd\">\n");
      out.write("          <div class=\"title capitalize\">caption</div>\n");
      out.write("          <input type=\"hidden\" name=\"userid\" id=\"userid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("          <input type=\"hidden\" name=\"username\" id=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfile.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\n");
      out.write("          <textarea autocomplete=\"off\" name=\"content\" id=\"post-desc\" placeholder=\"Enter the caption of the discussion\"></textarea>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"popbtns capitalize\">\n");
      out.write("          <div class=\"clear-btn\" id=\"popup-clear-btn\">\n");
      out.write("            Clear\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-rotate-left\"></i>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <!-- Use a div or any other element with a click event to trigger form submission -->\n");
      out.write("          <div class=\"post-btn\" id=\"popup-post-btn\" onclick=\"this.closest('form').submit();\">\n");
      out.write("            post discussion\n");
      out.write("          </div>\n");
      out.write("          <i class=\"fa-duotone fa-solid fa-check\"></i>\n");
      out.write("        </div>\n");
      out.write("      </form>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"comment-popup\">\n");
      out.write("  <div class=\"comment-container col-u\">\n");
      out.write("    <div class=\"drop-cmnt\"></div>\n");
      out.write("    <div class=\"post reactable reacted\">\n");
      out.write("      <div class=\"top\">\n");
      out.write("        <div class=\"post-details\">\n");
      out.write("          <a href=\"#\" class=\"img\"></a>\n");
      out.write("          <div class=\"details\">\n");
      out.write("            <a href=\"#\" class=\"name\">Himasha Chinthani</a>\n");
      out.write("            <div class=\"posted-date\">\n");
      out.write("              <i class=\"fa-light fa-clock\"></i>\n");
      out.write("              <div class=\"time\">\n");
      out.write("                <span class=\"value\" id=\"popup-time\">30</span> <!-- Will be updated by JS -->\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div>\n");
      out.write("          <input type=\"checkbox\" name=\"post-menu\" id=\"postMenu\" class=\"menuBtn\" />\n");
      out.write("          <span class=\"tip\">options</span>\n");
      out.write("          <label for=\"postMenu\" class=\"btn-2\">\n");
      out.write("            <i class=\"fa-regular fa-ellipsis-vertical\"></i>\n");
      out.write("          </label>\n");
      out.write("          <div class=\"post-dropDownMenu\">\n");
      out.write("            <ul>\n");
      out.write("              <li><a href=\"#\">report</a></li>\n");
      out.write("              <li><a href=\"#\">copy link</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"content\" id=\"popup-content\">\n");
      out.write("        Sri Lankan politics is the gift that keeps on giving...\n");
      out.write("      </div> <!-- Will be updated by JS -->\n");
      out.write("      <div class=\"reactions\">\n");
      out.write("        <button class=\"like btn\">\n");
      out.write("                    <span class=\"reactIcon\">\n");
      out.write("                        <i class=\"fa-solid fa-thumbs-up\"></i>\n");
      out.write("                    </span>\n");
      out.write("          <span>like</span>\n");
      out.write("          <span class=\"count\">0</span>\n");
      out.write("        </button>\n");
      out.write("        <button class=\"share btn\">\n");
      out.write("                    <span class=\"reactIcon\">\n");
      out.write("                        <i class=\"fa-duotone fa-solid fa-share-all\"></i>\n");
      out.write("                    </span>\n");
      out.write("          <span>share</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"add-cmnt row\">\n");
      out.write("      <div class=\"curr-user row\">\n");
      out.write("        <div class=\"prof-img\"></div>\n");
      out.write("      </div>\n");
      out.write("      <form action=\"PublishNewCommentServlet\" method=\"POST\">\n");
      out.write("        <textarea name=\"content\" id=\"add-cmnt\" placeholder=\"Comment here\" required></textarea>\n");
      out.write("        <button type=\"submit\" class=\"post-btn row btn capitalize\">\n");
      out.write("          Post\n");
      out.write("          <i class=\"fa-sharp fa-regular fa-paper-plane-top\"></i>\n");
      out.write("        </button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/sidebar1.css\">\n");
      out.write("\n");
      out.write("<div class=\"sidebar pd-1\">\n");
      out.write("    <div class=\"navs\">\n");
      out.write("        <ul>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-Home\" value=\"http://localhost:8080/Parlimate/GetPostListServlet\" checked/>\n");
      out.write("                <label for=\"nav-Home\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-house\"></i>Home</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-announcements\" value=\"http://localhost:8080/Parlimate/Announcements/GetListServlet?announcementId=123\" />\n");
      out.write("                <label for=\"nav-announcements\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-bullhorn\"></i>Announcements</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-fundraise\" value=\"http://localhost:8080/Parlimate/Fundraising/GetAllFundraisingApprovelServlet\" />\n");
      out.write("                <label for=\"nav-fundraise\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-coins\"></i>Fundraises</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-noti\" value=\"http://localhost:8080/Parlimate/Notification/notification.jsp\" />\n");
      out.write("                <label for=\"nav-noti\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-scale-balanced\"></i>Search & Compare</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-survey\" value=\"http://localhost:8080/Parlimate/Surveys/surveys.jsp\" />\n");
      out.write("                <label for=\"nav-survey\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-clipboard\"></i>Surveys</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-discusRoom\" value=\"http://localhost:8080/Parlimate/DiscussionRoom/discussion-room.jsp\" />\n");
      out.write("                <label for=\"nav-discusRoom\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-people-group\"></i>Meeting Room</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-help\" value=\"http://localhost:8080/Parlimate/Help/help.jsp\" />\n");
      out.write("                <label for=\"nav-help\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-headset\"></i>Help/Support</label>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function navigate(label) {\n");
      out.write("        const inputElement = label.previousElementSibling;\n");
      out.write("\n");
      out.write("        // Redirect to the input's value URL\n");
      out.write("        if (inputElement && inputElement.value) {\n");
      out.write("            window.location.href = inputElement.value;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function highlightCurrentPage() {\n");
      out.write("        const currentURL = window.location.href;\n");
      out.write("\n");
      out.write("        // Get all input elements in the sidebar\n");
      out.write("        const inputs = document.querySelectorAll('.sidebar input[type=\"radio\"]');\n");
      out.write("\n");
      out.write("        inputs.forEach(input => {\n");
      out.write("            // If the input's value matches the current URL, check the radio button\n");
      out.write("            if (input.value === currentURL) {\n");
      out.write("                input.checked = true;  // Check the radio input\n");
      out.write("                const label = input.nextElementSibling;\n");
      out.write("                if (label) {\n");
      out.write("                    label.classList.add('selected');  // Add the 'selected' class to the label\n");
      out.write("                }\n");
      out.write("            } else {\n");
      out.write("                const label = input.nextElementSibling;\n");
      out.write("                if (label) {\n");
      out.write("                    label.classList.remove('selected');  // Remove 'selected' class from other labels\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // Call the function when the page loads to highlight and check the current page's button\n");
      out.write("    window.onload = highlightCurrentPage;\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"logoutBtn capitalize\">\n");
      out.write("  <div class=\"cont\">\n");
      out.write("    <input type=\"checkbox\" name=\"logoutBtn\" id=\"logoutBtn\" onclick=\"logoutRedirect()\" />\n");
      out.write("    <label for=\"logoutBtn\">\n");
      out.write("      <i class=\"fa-solid fa-sign-out\"></i>\n");
      out.write("      <span>logout</span>\n");
      out.write("    </label>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  // Function to handle the redirect when the logout button is clicked\n");
      out.write("  function logoutRedirect() {\n");
      out.write("    // Check if the checkbox is checked (logout button clicked)\n");
      out.write("    if (document.getElementById('logoutBtn').checked) {\n");
      out.write("      window.location.href = 'http://localhost:8080/Parlimate/';\n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"./header.css\">\n");
      out.write("<style>\n");
      out.write("    .header .logo a img {\n");
      out.write("        height: 20px;\n");
      out.write("        transform: translateY(2px);\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"header pd-2\">\n");
      out.write("    <div class=\"start row\">\n");
      out.write("        <div class=\"sidebar-toggle-btn sideMenuBtn btn\">\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-bars\"></i>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"logo\">\n");
      out.write("            <a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("                <img src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" alt=\"ParlimateLogo\">\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"headerSearchBar row\">\n");
      out.write("        <input type=\"search\" name=\"mainSearch\" id=\"headerSearchBar\"\n");
      out.write("               placeholder=\"Search politicians, Political parties....\" />\n");
      out.write("        <label for=\"headerSearchBar\">\n");
      out.write("            <i class=\"fa-solid fa-magnifying-glass\"></i>\n");
      out.write("        </label>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"headerBtns\">\n");
      out.write("        <div class=\"headerBtn\">\n");
      out.write("            <input type=\"checkbox\" name=\"notifi\" id=\"notificationBtn\" />\n");
      out.write("            <label for=\"notificationBtn\" class=\"btn\">\n");
      out.write("                <i class=\"fa-solid fa-bell\"></i>\n");
      out.write("            </label>\n");
      out.write("            <span class=\"tip\">notifications</span>\n");
      out.write("            <div class=\"dropDownMenu\">\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\" class=\"notification\">\n");
      out.write("                            <div class=\"noti-img\"></div>\n");
      out.write("                            <div class=\"noti-title\">\n");
      out.write("                                <div class=\"notification-from\">\n");
      out.write("                                    Ranil wickramasinghe\n");
      out.write("                                </div>\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\n");
      out.write("											consectetur adipisicing elit. Qui,\n");
      out.write("											ullam. Quos aperiam in re</span>\n");
      out.write("                            </div>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\" class=\"notification\">\n");
      out.write("                            <div class=\"noti-img\"></div>\n");
      out.write("                            <div class=\"noti-title\">\n");
      out.write("                                <div class=\"notification-from\">\n");
      out.write("                                    Ranil wickramasinghe\n");
      out.write("                                </div>\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\n");
      out.write("											consectetur adipisicing elit. Qui,\n");
      out.write("											ullam. Quos aperiam in re</span>\n");
      out.write("                            </div>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\" class=\"notification\">\n");
      out.write("                            <div class=\"noti-img\"></div>\n");
      out.write("                            <div class=\"noti-title\">\n");
      out.write("                                <div class=\"notification-from\">\n");
      out.write("                                    Ranil wickramasinghe\n");
      out.write("                                </div>\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\n");
      out.write("											consectetur adipisicing elit. Qui,\n");
      out.write("											ullam. Quos aperiam in re</span>\n");
      out.write("                            </div>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <a href=\"./Announcements/announcements.html\" class=\"bottom-btn small-text capitalize\">\n");
      out.write("                    see all notifications\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"headerBtn\">\n");
      out.write("            <input type=\"checkbox\" name=\"profile\" id=\"profileBtn\" />\n");
      out.write("            <label for=\"profileBtn\" class=\"btn\">\n");
      out.write("                <i class=\"fa-solid fa-user\"></i>\n");
      out.write("            </label>\n");
      out.write("            <span class=\"tip\">profile</span>\n");
      out.write("            <div class=\"dropDownMenu\">\n");
      out.write("                <div class=\"profile\">\n");
      out.write("                    <a href=\"http://localhost:8080/Parlimate/Profile/profile.jsp\">\n");
      out.write("                        <div class=\"img\"></div>\n");
      out.write("                        <div class=\"details\">\n");
      out.write("                            <div class=\"name medium-text bold\">\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfile.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"email small-text\">\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <ul class=\"capitalize\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("									<span>\n");
      out.write("										<i class=\"fa-regular fa-gear\"></i>\n");
      out.write("									</span>\n");
      out.write("                            <span> account settings </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <div class=\"sep-line\"></div>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("									<span>\n");
      out.write("										<i class=\"fa-regular fa-circle-question\"></i>\n");
      out.write("									</span>\n");
      out.write("                            <span> help center </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("									<span>\n");
      out.write("										<i class=\"fa-regular fa-star\"></i>\n");
      out.write("									</span>\n");
      out.write("                            <span> upgrade plan </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <div class=\"sep-line\"></div>\n");
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"logoutBtn capitalize\">\n");
      out.write("                            <div class=\"cont\">\n");
      out.write("                                <input type=\"checkbox\" name=\"logoutBtn\" id=\"logoutBtn\" />\n");
      out.write("                                <label for=\"logoutBtn\">\n");
      out.write("                                    <i class=\"fa-solid fa-sign-out\"></i>\n");
      out.write("                                    <span>logout</span>\n");
      out.write("                                </label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("  <div class=\"pageTitles\">\n");
      out.write("    <h2 class=\"title\">Home</h2>\n");
      out.write("    <div class=\"subTitle\">Political activities and Discussions</div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"topContent\">\n");
      out.write("    <div class=\"social-btns col\">\n");
      out.write("      <div class=\"addPost-btn\">\n");
      out.write("        <div class=\"prof-img\"></div>\n");
      out.write("        <div class=\"content\">\n");
      out.write("          <div class=\"greeting\">\n");
      out.write("            Hello <span class=\"userName\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfile.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("          </div>\n");
      out.write("          <div>Got something to share?</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"req-fundraising col\">\n");
      out.write("        <div class=\"title capitalize row\">\n");
      out.write("          start a fundraise\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"weeklySurvey post votelist reactable\">\n");
      out.write("      <div class=\"post-head small-title\">\n");
      out.write("        <div class=\"post-title\">\n");
      out.write("          weekly survey\n");
      out.write("          <span class=\"btn round\"><i class=\"fa-solid fa-info\"></i></span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"survTime\">\n");
      out.write("          survey ends in :\n");
      out.write("          <span class=\"time\">\n");
      out.write("							<span class=\"sur-end-day\">5</span> days\n");
      out.write("							<span class=\"sur-end-hour\">12</span> hours\n");
      out.write("						</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"survey-title\">\n");
      out.write("        Who will be the next president of Sri Lanka?\n");
      out.write("      </div>\n");
      out.write("      <div class=\"surveyContent capitalize\">\n");
      out.write("					<span>\n");
      out.write("						<input type=\"radio\" name=\"week-survey\" id=\"survey-1\" />\n");
      out.write("						<label for=\"survey-1\">mahinda rajapakse</label>\n");
      out.write("					</span>\n");
      out.write("        <span>\n");
      out.write("						<input type=\"radio\" name=\"week-survey\" id=\"survey-2\" />\n");
      out.write("						<label for=\"survey-2\">ranil wickramasinghe</label>\n");
      out.write("					</span>\n");
      out.write("        <span>\n");
      out.write("						<input type=\"radio\" name=\"week-survey\" id=\"survey-3\" />\n");
      out.write("						<label for=\"survey-3\">anura kumara dissanayake</label>\n");
      out.write("					</span>\n");
      out.write("        <span>\n");
      out.write("						<input type=\"radio\" name=\"week-survey\" id=\"survey-4\" />\n");
      out.write("						<label for=\"survey-4\">sajith wickramasinghe</label>\n");
      out.write("					</span>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"reactions\">\n");
      out.write("        <button class=\"btn\" id=\"vote-btn\">\n");
      out.write("          submit my vote\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"last-surveys\">\n");
      out.write("      <div class=\"post-head medium-title\">\n");
      out.write("        Last surevy results\n");
      out.write("      </div>\n");
      out.write("      <div class=\"content\">\n");
      out.write("        fill this content with the last survey results\n");
      out.write("      </div>\n");
      out.write("      <a href=\"#\" class=\"past-surv-link small-text\">See past surevys</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <ul class=\"post-list\" style=\"list-style-type: none; padding: 0; margin-right: 20px; gap: 1.5rem;\">\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  </ul>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("<script>function openCommentPopup(content, datetime) {\n");
      out.write("  // Update the popup content and datetime\n");
      out.write("  document.getElementById(\"popup-content\").innerText = content;\n");
      out.write("  document.getElementById(\"popup-time\").innerText = datetime;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<script src=\"script.js\"></script>\n");
      out.write("<script src=\"home.js\"></script>\n");
      out.write("<script src=\"home.js\"></script>\n");
      out.write("<script src=\"fund-pop.js\"></script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /index/header/header.jsp(19,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("http://localhost:8080/Parlimate/GetPostListServlet");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /index/header/header.jsp(20,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/assets/images/logo.png");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /Home.jsp(350,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("post");
    // /Home.jsp(350,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Home.jsp(350,4) '${allposts}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${allposts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("      <div class=\"post reactable reacted\">\n");
          out.write("        <div class=\"top\">\n");
          out.write("          <div class=\"post-details\">\n");
          out.write("            <a href=\"#\" class=\"img\"></a>\n");
          out.write("            <div class=\"details\">\n");
          out.write("              <a href=\"#\" class=\"name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("              <div class=\"posted-date\">\n");
          out.write("                <i class=\"fa-light fa-clock\"></i>\n");
          out.write("                <div class=\"time\">\n");
          out.write("                  <span class=\"value\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.datetime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("                </div>\n");
          out.write("              </div>\n");
          out.write("            </div>\n");
          out.write("          </div>\n");
          out.write("          <div>\n");
          out.write("            <input type=\"checkbox\" name=\"post-menu\" id=\"postMenu\" class=\"menuBtn\" />\n");
          out.write("            <span class=\"tip\">options</span>\n");
          out.write("            <label for=\"postMenu\" class=\"btn-2\">\n");
          out.write("              <i class=\"fa-regular fa-ellipsis-vertical\"></i>\n");
          out.write("            </label>\n");
          out.write("            <div class=\"post-dropDownMenu\">\n");
          out.write("              <ul>\n");
          out.write("                <li><a href=\"#\">report</a></li>\n");
          out.write("                <li><a href=\"#\">copy link</a></li>\n");
          out.write("              </ul>\n");
          out.write("            </div>\n");
          out.write("          </div>\n");
          out.write("        </div>\n");
          out.write("        <div class=\"content\">\n");
          out.write("            ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("        </div>\n");
          out.write("        <div class=\"reactions\">\n");
          out.write("          <button class=\"like btn\">\n");
          out.write("                    <span class=\"reactIcon\">\n");
          out.write("                        <i class=\"fa-solid fa-thumbs-up\"></i>\n");
          out.write("                    </span>\n");
          out.write("            <span>like</span>\n");
          out.write("            <span class=\"count\">32k</span>\n");
          out.write("          </button>\n");
          out.write("          <button class=\"comment btn\" onclick=\"openCommentPopup('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.datetime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">\n");
          out.write("                    <span class=\"reactIcon\">\n");
          out.write("                        <i class=\"fa-solid fa-message\"></i>\n");
          out.write("                    </span>\n");
          out.write("            <span>comment</span>\n");
          out.write("            <span class=\"count\">1k</span>\n");
          out.write("          </button>\n");
          out.write("          <button class=\"share btn\">\n");
          out.write("                    <span class=\"reactIcon\">\n");
          out.write("                        <i class=\"fa-duotone fa-solid fa-share-all\"></i>\n");
          out.write("                    </span>\n");
          out.write("            <span>share</span>\n");
          out.write("          </button>\n");
          out.write("        </div>\n");
          out.write("      </div>\n");
          out.write("      &nbsp;&nbsp;\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager());
    return false;
  }
}
