/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-11-28 15:04:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDateTime;

public final class postsDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:escapeXml", org.apache.taglibs.standard.functions.Functions.class, "escapeXml", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Group%20Project%20second%20year/JAR%20Files-20241102T061912Z-001/JAR%20Files/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("jar:file:/D:/Group%20Project%20second%20year/JAR%20Files-20241102T061912Z-001/JAR%20Files/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1730528383482L));
    _jspx_dependants.put("/index/sidebar.jsp", Long.valueOf(1732766106308L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.time.LocalDateTime");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Announcements</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* General Styles */\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #f5f7fb;\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        body.sidebar-deactive .sidebar {\r\n");
      out.write("            transform: translateX(-100%);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .top-bar {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("            margin-top: 80px;\r\n");
      out.write("        }\r\n");
      out.write("        .button-home {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 12px 25px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-home:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            color: #3a3a3a;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Search Input Styles */\r\n");
      out.write("        #searchInput {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 200px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            margin-left: 250px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #searchInput:focus {\r\n");
      out.write("            border-color: #007bff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Announcement List Styles */\r\n");
      out.write("        .post-list {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin-left: 300px;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .post-item {\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .post-item:hover {\r\n");
      out.write("            outline: 1px solid rgb(185, 185, 185);\r\n");
      out.write("            border-left: 0.75rem solid #5490FF;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .post-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-info h3 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-info p {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #888;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-content {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Button Styles */\r\n");
      out.write("        .post-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button {\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 0; /* Adjusted padding for consistent height */\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("            width: 100px; /* Ensures both buttons have the same width */\r\n");
      out.write("            height: 40px; /* Ensures both buttons have the same height */\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-update {\r\n");
      out.write("            background-color: #6a5acd; /* Light purple */\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-update:hover {\r\n");
      out.write("            background-color: #5b4ab5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-delete {\r\n");
      out.write("            background-color: #f44336; /* Red */\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-delete:hover {\r\n");
      out.write("            background-color: #e53935;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Popup Modal Styles */\r\n");
      out.write("        .popup-modal {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.5);\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popup .close-btn {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 10px;\r\n");
      out.write("            right: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .formSection {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .formSection label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .formSection input, .formSection textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .popbtns {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-btn {\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #6a5acd;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .post-btn:hover {\r\n");
      out.write("            background-color: #5b4ab5;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Announcements | Parlimate</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"index.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"index/sidebar1.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"index/header/header.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"container.css\" />\r\n");
      out.write("    <!-- <link rel=\"stylesheet\"\r\n");
      out.write("href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\"\r\n");
      out.write("/> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- icons -->\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            data-purpose=\"Layout StyleSheet\"\r\n");
      out.write("            title=\"Web Awesome\"\r\n");
      out.write("            href=\"/css/app-wa-09b459cf485d4b1f3304947240314c05.css?vsn=d\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/all.css\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-duotone-solid.css\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-thin.css\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-solid.css\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-regular.css\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-light.css\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/sidebar1.css\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar pd-1\">\r\n");
      out.write("    <div class=\"navs\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-Home\" value=\"http://localhost:8080/Parlimate/Home.jsp\" checked/>\r\n");
      out.write("                <label for=\"nav-Home\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-house\"></i>Home</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-announcements\" value=\"http://localhost:8080/Parlimate/Announcements/GetListServlet?announcementId=123\" />\r\n");
      out.write("                <label for=\"nav-announcements\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-bullhorn\"></i>Announcements</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-fundraise\" value=\"http://localhost:8080/Parlimate/Fundraising/fundraising.jsp\" />\r\n");
      out.write("                <label for=\"nav-fundraise\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-coins\"></i>Fundraises</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-noti\" value=\"http://localhost:8080/Parlimate/Notification/notification.jsp\" />\r\n");
      out.write("                <label for=\"nav-noti\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-scale-balanced\"></i>Search & Compare</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-survey\" value=\"http://localhost:8080/Parlimate/Surveys/surveys.jsp\" />\r\n");
      out.write("                <label for=\"nav-survey\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-clipboard\"></i>Surveys</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-discusRoom\" value=\"http://localhost:8080/Parlimate/DiscussionRoom/discussion-room.jsp\" />\r\n");
      out.write("                <label for=\"nav-discusRoom\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-people-group\"></i>Meeting Room</label>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-help\" value=\"http://localhost:8080/Parlimate/Help/help.jsp\" />\r\n");
      out.write("                <label for=\"nav-help\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-headset\"></i>Help/Support</label>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function navigate(label) {\r\n");
      out.write("        const inputElement = label.previousElementSibling;\r\n");
      out.write("\r\n");
      out.write("        // Redirect to the input's value URL\r\n");
      out.write("        if (inputElement && inputElement.value) {\r\n");
      out.write("            window.location.href = inputElement.value;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function highlightCurrentPage() {\r\n");
      out.write("        const currentURL = window.location.href;\r\n");
      out.write("\r\n");
      out.write("        // Get all input elements in the sidebar\r\n");
      out.write("        const inputs = document.querySelectorAll('.sidebar input[type=\"radio\"]');\r\n");
      out.write("\r\n");
      out.write("        inputs.forEach(input => {\r\n");
      out.write("            // If the input's value matches the current URL, check the radio button\r\n");
      out.write("            if (input.value === currentURL) {\r\n");
      out.write("                input.checked = true;  // Check the radio input\r\n");
      out.write("                const label = input.nextElementSibling;\r\n");
      out.write("                if (label) {\r\n");
      out.write("                    label.classList.add('selected');  // Add the 'selected' class to the label\r\n");
      out.write("                }\r\n");
      out.write("            } else {\r\n");
      out.write("                const label = input.nextElementSibling;\r\n");
      out.write("                if (label) {\r\n");
      out.write("                    label.classList.remove('selected');  // Remove 'selected' class from other labels\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Call the function when the page loads to highlight and check the current page's button\r\n");
      out.write("    window.onload = highlightCurrentPage;\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header pd-2\">\r\n");
      out.write("    <div class=\"start row\">\r\n");
      out.write("        <div class=\"sidebar-toggle-btn sideMenuBtn btn\">\r\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-bars\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"./index.html\">\r\n");
      out.write("                PARLIMATE\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"headerSearchBar row\">\r\n");
      out.write("        <input type=\"search\" name=\"mainSearch\" id=\"headerSearchBar\"\r\n");
      out.write("               placeholder=\"Search politicians, Political parties....\" />\r\n");
      out.write("        <label for=\"headerSearchBar\">\r\n");
      out.write("            <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n");
      out.write("        </label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"headerBtns\">\r\n");
      out.write("        <div class=\"headerBtn\">\r\n");
      out.write("            <input type=\"checkbox\" name=\"notifi\" id=\"notificationBtn\" />\r\n");
      out.write("            <label for=\"notificationBtn\" class=\"btn\">\r\n");
      out.write("                <i class=\"fa-solid fa-bell\"></i>\r\n");
      out.write("            </label>\r\n");
      out.write("            <span class=\"tip\">notifications</span>\r\n");
      out.write("            <div class=\"dropDownMenu\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" class=\"notification\">\r\n");
      out.write("                            <div class=\"noti-img\"></div>\r\n");
      out.write("                            <div class=\"noti-title\">\r\n");
      out.write("                                <div class=\"notification-from\">\r\n");
      out.write("                                    Ranil wickramasinghe\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\r\n");
      out.write("											consectetur adipisicing elit. Qui,\r\n");
      out.write("											ullam. Quos aperiam in re</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" class=\"notification\">\r\n");
      out.write("                            <div class=\"noti-img\"></div>\r\n");
      out.write("                            <div class=\"noti-title\">\r\n");
      out.write("                                <div class=\"notification-from\">\r\n");
      out.write("                                    Ranil wickramasinghe\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\r\n");
      out.write("											consectetur adipisicing elit. Qui,\r\n");
      out.write("											ullam. Quos aperiam in re</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" class=\"notification\">\r\n");
      out.write("                            <div class=\"noti-img\"></div>\r\n");
      out.write("                            <div class=\"noti-title\">\r\n");
      out.write("                                <div class=\"notification-from\">\r\n");
      out.write("                                    Ranil wickramasinghe\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\r\n");
      out.write("											consectetur adipisicing elit. Qui,\r\n");
      out.write("											ullam. Quos aperiam in re</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"./Announcements/announcements.html\" class=\"bottom-btn small-text capitalize\">\r\n");
      out.write("                    see all notifications\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"headerBtn\">\r\n");
      out.write("            <input type=\"checkbox\" name=\"profile\" id=\"profileBtn\" />\r\n");
      out.write("            <label for=\"profileBtn\" class=\"btn\">\r\n");
      out.write("                <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("            </label>\r\n");
      out.write("            <span class=\"tip\">profile</span>\r\n");
      out.write("            <div class=\"dropDownMenu\">\r\n");
      out.write("                <div class=\"profile\">\r\n");
      out.write("                    <a href=\"../Profile/profile.html\">\r\n");
      out.write("                        <div class=\"img\"></div>\r\n");
      out.write("                        <div class=\"details\">\r\n");
      out.write("                            <div class=\"name medium-text bold\">\r\n");
      out.write("                                Naleeka Kumarasinghe\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"email small-text\">\r\n");
      out.write("                                knaleeka845@gmail.com\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"capitalize\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<i class=\"fa-regular fa-gear\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("                            <span> account settings </span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <div class=\"sep-line\"></div>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<i class=\"fa-regular fa-circle-question\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("                            <span> help center </span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("                            <span> upgrade plan </span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <div class=\"sep-line\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"logoutBtn capitalize\">\r\n");
      out.write("                            <div class=\"cont\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"logoutBtn\" id=\"logoutBtn\" />\r\n");
      out.write("                                <label for=\"logoutBtn\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-sign-out\"></i>\r\n");
      out.write("                                    <span>logout</span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"top-bar\">\r\n");
      out.write("\r\n");
      out.write("    <a href=\"index.jsp\" class=\"button-home\">Go to Home</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>My Posts</h2>\r\n");
      out.write("\r\n");
      out.write("<input type=\"text\" id=\"searchInput\" placeholder=\"Search posts...\" onkeyup=\"filterAnnouncements()\">\r\n");
      out.write("\r\n");
      out.write("<ul class=\"post-list\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<!-- Update Announcement Popup Modal -->\r\n");
      out.write("<div class=\"popup-modal\" id=\"editPopup\">\r\n");
      out.write("    <div class=\"popup\">\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("            <span>Edit Post</span>\r\n");
      out.write("            <button class=\"close-btn\" onclick=\"closeEditPopup()\">\r\n");
      out.write("                <i class=\"fa-solid fa-times\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"UpdatePostServlet\" method=\"post\">\r\n");
      out.write("            <!-- Hidden fields for post ID and user ID -->\r\n");
      out.write("            <input type=\"hidden\" name=\"postid\" id=\"postid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${postid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("            <input type=\"hidden\" name=\"userid\" id=\"userid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("            <!-- Content Section -->\r\n");
      out.write("            <div class=\"formSection\">\r\n");
      out.write("                <label for=\"editContent\">Content</label>\r\n");
      out.write("                <textarea id=\"editContent\" name=\"content\" placeholder=\"Edit content here...\" required></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Save Button -->\r\n");
      out.write("            <div class=\"popbtns\">\r\n");
      out.write("                <button type=\"submit\" class=\"post-btn\">Save Changes</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    let sideMenuBtns = document.querySelectorAll(\".sideMenuBtn\");\r\n");
      out.write("    const body = document.querySelector(\"body\");\r\n");
      out.write("    const navRadios = document.querySelectorAll('input[name=\"nav\"]');\r\n");
      out.write("\r\n");
      out.write("    sideMenuBtns.forEach((btn) => {\r\n");
      out.write("        btn.addEventListener(\"click\", () => {\r\n");
      out.write("            if (body.classList.contains(\"sidebar-deactive\")) {\r\n");
      out.write("                body.classList.remove(\"sidebar-deactive\");\r\n");
      out.write("            } else {\r\n");
      out.write("                body.classList.add(\"sidebar-deactive\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    navRadios.forEach(radio => {\r\n");
      out.write("        radio.addEventListener('change', (event) => {\r\n");
      out.write("            const selectedValue = event.target.value;\r\n");
      out.write("            if (selectedValue) {\r\n");
      out.write("                window.location.href = selectedValue; // Redirect to the selected page\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    // Function to open the modal and populate the form\r\n");
      out.write("    function openEditPopup(postid, userid, content, datetime) {\r\n");
      out.write("        // Show the popup modal\r\n");
      out.write("        document.getElementById('editPopup').style.display = 'flex';\r\n");
      out.write("\r\n");
      out.write("        // Remove milliseconds from the datetime value\r\n");
      out.write("        const formattedDatetime = datetime.substring(0, 16);\r\n");
      out.write("\r\n");
      out.write("        // Populate the form with the current announcement data\r\n");
      out.write("        document.getElementById('postid').value = postid;\r\n");
      out.write("        document.getElementById('userid').value = userid;\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('editContent').value = content;\r\n");
      out.write("        document.getElementById('editDatetime').value = formattedDatetime;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to close the popup modal\r\n");
      out.write("    function closeEditPopup() {\r\n");
      out.write("        // Hide the popup modal\r\n");
      out.write("        document.getElementById('editPopup').style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to filter announcements\r\n");
      out.write("    function filterAnnouncements() {\r\n");
      out.write("        const input = document.getElementById(\"searchInput\").value.toUpperCase();\r\n");
      out.write("        const listItems = document.querySelectorAll(\".announcement-item\");\r\n");
      out.write("\r\n");
      out.write("        listItems.forEach(item => {\r\n");
      out.write("            const text = item.textContent || item.innerText;\r\n");
      out.write("            item.style.display = text.toUpperCase().includes(input) ? \"\" : \"none\";\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"../script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /postsDetail.jsp(423,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("post");
    // /postsDetail.jsp(423,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/postsDetail.jsp(423,4) '${allposts}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${allposts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <li class=\"post-item\">\r\n");
          out.write("            <div class=\"post-header\">\r\n");
          out.write("                <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                <div class=\"post-info\">\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("                    <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.datetime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("                </div>\r\n");
          out.write("            </div>\r\n");
          out.write("            <div class=\"post-content\">\r\n");
          out.write("                    ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("            <div class=\"post-actions\">\r\n");
          out.write("                <!-- Update Button triggers the popup modal with announcement data -->\r\n");
          out.write("                <button class=\"button button-update\" onclick=\"openEditPopup('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.postId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("',  '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(post.content)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.datetime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">Update</button>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("                <!-- Delete Button -->\r\n");
          out.write("                <form action=\"DeletePostServlet\" method=\"post\" onsubmit=\"return confirm('Are you sure you want to delete this post?');\" style=\"display:inline;\">\r\n");
          out.write("                    <input type=\"hidden\" name=\"postid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.postId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("                    <button type=\"submit\" class=\"button button-delete\">Delete</button>\r\n");
          out.write("                </form>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("            </div>\r\n");
          out.write("        </li>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
