/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2025-04-05 04:42:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Surveys;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class surveys_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1725271156711L));
    _jspx_dependants.put("/index/sidebar.jsp", Long.valueOf(1738291084037L));
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/index/header/header.jsp", Long.valueOf(1738291078541L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    HttpSession session1 = request.getSession(false);
    if (session1 == null || session1.getAttribute("user") == null) {
        // User is not logged in, redirect to login page
        response.sendRedirect("../index.jsp");
        return;
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("    <title>SURVEYS | Parlimate</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../index.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"../index/sidebar1.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"../index/header/header.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"../container.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"./survey.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"./surv-popup.css\" />\n");
      out.write("    <!-- icons -->\n");
      out.write("    <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            data-purpose=\"Layout StyleSheet\"\n");
      out.write("            title=\"Web Awesome\"\n");
      out.write("            href=\"/css/app-wa-09b459cf485d4b1f3304947240314c05.css?vsn=d\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/all.css\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        google.charts.load('current', {'packages':['bar']});\n");
      out.write("        google.charts.setOnLoadCallback(drawStuff);\n");
      out.write("\n");
      out.write("        function drawStuff() {\n");
      out.write("            var data = new google.visualization.arrayToDataTable([\n");
      out.write("                ['Province', 'Percentage'],\n");
      out.write("                [\"Western \", 40],\n");
      out.write("                [\"Central\", 20],\n");
      out.write("                [\"Southern\", 10],\n");
      out.write("                [\"Northern\", 2],\n");
      out.write("                [\"Eastern\", 3],\n");
      out.write("                [\"Uva\",5],\n");
      out.write("                [\"Sabaragamuwa\",8],\n");
      out.write("                [\"North Western\",3],\n");
      out.write("                [\"North Central\",9]\n");
      out.write("            ]);\n");
      out.write("\n");
      out.write("            var options = {\n");
      out.write("                width: 500,\n");
      out.write("                legend: { position: 'none' },\n");
      out.write("                chart: {},\n");
      out.write("                bars: 'horizontal',\n");
      out.write("                axes: {\n");
      out.write("                    x: {\n");
      out.write("                        0: { side: 'top', label: 'Percentage'}\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                bar: { groupWidth: \"90%\" },\n");
      out.write("                colors: ['#D8BFD8']\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            var chart = new google.charts.Bar(document.getElementById('top_x_div'));\n");
      out.write("            chart.draw(data, options);\n");
      out.write("        };\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body class=\"\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/sidebar1.css\">\n");
      out.write("\n");
      out.write("<div class=\"sidebar pd-1\">\n");
      out.write("    <div class=\"navs\">\n");
      out.write("        <ul>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-Home\" value=\"http://localhost:8080/Parlimate/GetPostListServlet\" checked/>\n");
      out.write("                <label for=\"nav-Home\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-house\"></i>Home</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-announcements\" value=\"http://localhost:8080/Parlimate/Announcements/GetListServlet?announcementId=123\" />\n");
      out.write("                <label for=\"nav-announcements\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-bullhorn\"></i>Announcements</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-fundraise\" value=\"http://localhost:8080/Parlimate/Fundraising/fundraising.jsp\" />\n");
      out.write("                <label for=\"nav-fundraise\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-coins\"></i>Fundraises</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-noti\" value=\"http://localhost:8080/Parlimate/Notification/notification.jsp\" />\n");
      out.write("                <label for=\"nav-noti\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-scale-balanced\"></i>Search & Compare</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-survey\" value=\"http://localhost:8080/Parlimate/Surveys/surveys.jsp\" />\n");
      out.write("                <label for=\"nav-survey\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-clipboard\"></i>Surveys</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-discusRoom\" value=\"http://localhost:8080/Parlimate/DiscussionRoom/discussion-room.jsp\" />\n");
      out.write("                <label for=\"nav-discusRoom\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-people-group\"></i>Meeting Room</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-help\" value=\"http://localhost:8080/Parlimate/Help/help.jsp\" />\n");
      out.write("                <label for=\"nav-help\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-headset\"></i>Help/Support</label>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function navigate(label) {\n");
      out.write("        const inputElement = label.previousElementSibling;\n");
      out.write("\n");
      out.write("        // Redirect to the input's value URL\n");
      out.write("        if (inputElement && inputElement.value) {\n");
      out.write("            window.location.href = inputElement.value;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function highlightCurrentPage() {\n");
      out.write("        const currentURL = window.location.href;\n");
      out.write("\n");
      out.write("        // Get all input elements in the sidebar\n");
      out.write("        const inputs = document.querySelectorAll('.sidebar input[type=\"radio\"]');\n");
      out.write("\n");
      out.write("        inputs.forEach(input => {\n");
      out.write("            // If the input's value matches the current URL, check the radio button\n");
      out.write("            if (input.value === currentURL) {\n");
      out.write("                input.checked = true;  // Check the radio input\n");
      out.write("                const label = input.nextElementSibling;\n");
      out.write("                if (label) {\n");
      out.write("                    label.classList.add('selected');  // Add the 'selected' class to the label\n");
      out.write("                }\n");
      out.write("            } else {\n");
      out.write("                const label = input.nextElementSibling;\n");
      out.write("                if (label) {\n");
      out.write("                    label.classList.remove('selected');  // Remove 'selected' class from other labels\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // Call the function when the page loads to highlight and check the current page's button\n");
      out.write("    window.onload = highlightCurrentPage;\n");
      out.write("</script>\n");
      out.write('\n');
      out.write("<link rel=\"stylesheet\" href=\"./header.css\">\n");
      out.write("<style>\n");
      out.write("    .header .logo a img {\n");
      out.write("        height: 20px;\n");
      out.write("        transform: translateY(2px);\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"header pd-2\">\n");
      out.write("    <div class=\"start row\">\n");
      out.write("        <div class=\"sidebar-toggle-btn sideMenuBtn btn\">\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-bars\"></i>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"logo\">\n");
      out.write("            <a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("                <img src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" alt=\"ParlimateLogo\">\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"headerSearchBar row\">\n");
      out.write("        <input type=\"search\" name=\"mainSearch\" id=\"headerSearchBar\"\n");
      out.write("               placeholder=\"Search politicians, Political parties....\" />\n");
      out.write("        <label for=\"headerSearchBar\">\n");
      out.write("            <i class=\"fa-solid fa-magnifying-glass\"></i>\n");
      out.write("        </label>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"headerBtns\">\n");
      out.write("        <div class=\"headerBtn\">\n");
      out.write("            <input type=\"checkbox\" name=\"notifi\" id=\"notificationBtn\" />\n");
      out.write("            <label for=\"notificationBtn\" class=\"btn\">\n");
      out.write("                <i class=\"fa-solid fa-bell\"></i>\n");
      out.write("            </label>\n");
      out.write("            <span class=\"tip\">notifications</span>\n");
      out.write("            <div class=\"dropDownMenu\">\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\" class=\"notification\">\n");
      out.write("                            <div class=\"noti-img\"></div>\n");
      out.write("                            <div class=\"noti-title\">\n");
      out.write("                                <div class=\"notification-from\">\n");
      out.write("                                    Ranil wickramasinghe\n");
      out.write("                                </div>\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\n");
      out.write("											consectetur adipisicing elit. Qui,\n");
      out.write("											ullam. Quos aperiam in re</span>\n");
      out.write("                            </div>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\" class=\"notification\">\n");
      out.write("                            <div class=\"noti-img\"></div>\n");
      out.write("                            <div class=\"noti-title\">\n");
      out.write("                                <div class=\"notification-from\">\n");
      out.write("                                    Ranil wickramasinghe\n");
      out.write("                                </div>\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\n");
      out.write("											consectetur adipisicing elit. Qui,\n");
      out.write("											ullam. Quos aperiam in re</span>\n");
      out.write("                            </div>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\" class=\"notification\">\n");
      out.write("                            <div class=\"noti-img\"></div>\n");
      out.write("                            <div class=\"noti-title\">\n");
      out.write("                                <div class=\"notification-from\">\n");
      out.write("                                    Ranil wickramasinghe\n");
      out.write("                                </div>\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\n");
      out.write("											consectetur adipisicing elit. Qui,\n");
      out.write("											ullam. Quos aperiam in re</span>\n");
      out.write("                            </div>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <a href=\"./Announcements/announcements.html\" class=\"bottom-btn small-text capitalize\">\n");
      out.write("                    see all notifications\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"headerBtn\">\n");
      out.write("            <input type=\"checkbox\" name=\"profile\" id=\"profileBtn\" />\n");
      out.write("            <label for=\"profileBtn\" class=\"btn\">\n");
      out.write("                <i class=\"fa-solid fa-user\"></i>\n");
      out.write("            </label>\n");
      out.write("            <span class=\"tip\">profile</span>\n");
      out.write("            <div class=\"dropDownMenu\">\n");
      out.write("                <div class=\"profile\">\n");
      out.write("                    <a href=\"http://localhost:8080/Parlimate/Profile/profile.jsp\">\n");
      out.write("                        <div class=\"img\"></div>\n");
      out.write("                        <div class=\"details\">\n");
      out.write("                            <div class=\"name medium-text bold\">\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfile.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"email small-text\">\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <ul class=\"capitalize\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("									<span>\n");
      out.write("										<i class=\"fa-regular fa-gear\"></i>\n");
      out.write("									</span>\n");
      out.write("                            <span> account settings </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <div class=\"sep-line\"></div>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("									<span>\n");
      out.write("										<i class=\"fa-regular fa-circle-question\"></i>\n");
      out.write("									</span>\n");
      out.write("                            <span> help center </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("									<span>\n");
      out.write("										<i class=\"fa-regular fa-star\"></i>\n");
      out.write("									</span>\n");
      out.write("                            <span> upgrade plan </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <div class=\"sep-line\"></div>\n");
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"logoutBtn capitalize\">\n");
      out.write("                            <div class=\"cont\">\n");
      out.write("                                <input type=\"checkbox\" name=\"logoutBtn\" id=\"logoutBtn\" />\n");
      out.write("                                <label for=\"logoutBtn\">\n");
      out.write("                                    <i class=\"fa-solid fa-sign-out\"></i>\n");
      out.write("                                    <span>logout</span>\n");
      out.write("                                </label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container col\">\n");
      out.write("    <div class=\"pageTitles\">\n");
      out.write("        <h2 class=\"title\">Surveys</h2>\n");
      out.write("        <div class=\"subTitle\">\n");
      out.write("            Surveys conducted by Parlimate\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"announcements col\">\n");
      out.write("            <div class=\"subTitle1\">\n");
      out.write("                Ongoing Surveys\n");
      out.write("            </div>\n");
      out.write("            <div class=\"survey\">\n");
      out.write("                <div style=\"display: flex; justify-content: space-between;margin-bottom: 4px;\">\n");
      out.write("                    <span style=\"text-align: left;font-size: medium;\">&nbsp;&nbsp;<strong>Survey Name : Who will be the next president of Sri Lanka?</strong></span>\n");
      out.write("                    <span style=\"text-align: right;font-size: medium;\"><strong>\n");
      out.write("                        <button class=\"request-survey\">\n");
      out.write("                            <span>+ Request Survey</span>\n");
      out.write("                        </button>\n");
      out.write("                        <br>\n");
      out.write("\n");
      out.write("                        <!-- Survey Popup (Hidden by Default) -->\n");
      out.write("                    <form action=\"CreateSurveyRequestServlet\" method=\"post\" class=\"popup-f\" id=\"popup-f\">\n");
      out.write("\n");
      out.write("    <div id=\"surveyPopup\" class=\"survey-popup\">\n");
      out.write("        <div class=\"popup-content\">\n");
      out.write("            <div class=\"popup-header\">\n");
      out.write("                <div class=\"title\">Create Survey Question</div>\n");
      out.write("                <div id=\"closePopup\" class=\"close-btn\">\n");
      out.write("                    <i class=\"fa-solid fa-xmark\"></i>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"separator\"></div>\n");
      out.write("            <div class=\"body col\">\n");
      out.write("                <div class=\"survey-question field\">\n");
      out.write("                    <label for=\"survey-question\" class=\"title\">Question</label>\n");
      out.write("                    <input type=\"text\" required placeholder=\"Enter your question here\" name=\"questiontext\" id=\"survey-question\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"survey-answer field\">\n");
      out.write("                    <label for=\"answer01\" class=\"title\">Answer 1</label>\n");
      out.write("                    <input type=\"text\" required placeholder=\"Enter first answer\" name=\"answer01\" id=\"answer01\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"survey-answer field\">\n");
      out.write("                    <label for=\"answer02\" class=\"title\">Answer 2</label>\n");
      out.write("                    <input type=\"text\" required placeholder=\"Enter second answer\" name=\"answer02\" id=\"answer02\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"survey-answer field\">\n");
      out.write("                    <label for=\"answer03\" class=\"title\">Answer 3</label>\n");
      out.write("                    <input type=\"text\" required placeholder=\"Enter third answer\" name=\"answer03\" id=\"answer03\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"survey-answer field\">\n");
      out.write("                    <label for=\"answer04\" class=\"title\">Answer 4</label>\n");
      out.write("                    <input type=\"text\" required placeholder=\"Enter fourth answer\" name=\"answer04\" id=\"answer04\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"bottom row\">\n");
      out.write("                <button type=\"button\" id=\"cancelPopup\" class=\"form-btn cancel-btn\">Cancel</button>\n");
      out.write("                <button type=\"submit\" id=\"submitSurvey\" class=\"form-btn submit-btn\">Submit</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("                        <!-- Request Survey Button -->\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"separator\"></div>\n");
      out.write("                        Survey Number : #01AAAA\n");
      out.write("                    </strong>&nbsp;&nbsp;</span>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"weeklySurvey post votelist reactable\">\n");
      out.write("                    <div class=\"post-head small-title\">\n");
      out.write("                        <div class=\"post-title\">\n");
      out.write("                            weekly survey 1\n");
      out.write("                            <span class=\"btn round\"><i class=\"fa-solid fa-info\"></i></span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"survTime\">\n");
      out.write("                            survey ends in :\n");
      out.write("                            <span class=\"time\">\n");
      out.write("                                <span class=\"sur-end-day\">5</span> days\n");
      out.write("                                <span class=\"sur-end-hour\">12</span> hours\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"survey-title\">\n");
      out.write("                        Who will be the next president of Sri Lanka?\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"surveyContent capitalize\">\n");
      out.write("                        <span>\n");
      out.write("                            <input type=\"radio\" name=\"week-survey\" id=\"survey-1\" />\n");
      out.write("                            <label for=\"survey-1\">mahinda rajapakse</label>\n");
      out.write("                        </span>\n");
      out.write("                        <span>\n");
      out.write("                            <input type=\"radio\" name=\"week-survey\" id=\"survey-2\" />\n");
      out.write("                            <label for=\"survey-2\">ranil wickramasinghe</label>\n");
      out.write("                        </span>\n");
      out.write("                        <span>\n");
      out.write("                            <input type=\"radio\" name=\"week-survey\" id=\"survey-3\" />\n");
      out.write("                            <label for=\"survey-3\">anura kumara dissanayake</label>\n");
      out.write("                        </span>\n");
      out.write("                        <span>\n");
      out.write("                            <input type=\"radio\" name=\"week-survey\" id=\"survey-4\" />\n");
      out.write("                            <label for=\"survey-4\">sajith wickramasinghe</label>\n");
      out.write("                        </span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"reactions\">\n");
      out.write("                        <button class=\"btn\" id=\"vote-btn\">\n");
      out.write("                            submit my vote\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"current-results\" style=\"margin-bottom: 15px;\">\n");
      out.write("                    <div class=\"weeklySurvey post votelist reactable results\">\n");
      out.write("                        <div class=\"post-head small-title\">\n");
      out.write("                            <div class=\"post-title\">\n");
      out.write("                                weekly survey 1 - current results\n");
      out.write("                                <span class=\"btn round\"><i class=\"fa-solid fa-info\"></i></span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"survey-title\">\n");
      out.write("                            Who will be the next president of Sri Lanka?\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"surveyContent capitalize\">\n");
      out.write("                            <div id=\"candidate\">\n");
      out.write("                                <span id=\"percentage\"><strong>45%</strong></span>\n");
      out.write("                                <span id=\"name\">Mahinda Rajapakse</span>\n");
      out.write("                            </div>\n");
      out.write("                            <div id=\"candidate\">\n");
      out.write("                                <span id=\"percentage\"><strong>30%</strong></span>\n");
      out.write("                                <span id=\"name\">Ranil Wickramasinghe</span>\n");
      out.write("                            </div>\n");
      out.write("                            <div id=\"candidate\">\n");
      out.write("                                <span id=\"percentage\"><strong>15%</strong></span>\n");
      out.write("                                <span id=\"name\">Anura Kumara Dissanayake</span>\n");
      out.write("                            </div>\n");
      out.write("                            <div id=\"candidate\">\n");
      out.write("                                <span id=\"percentage\"><strong>10%</strong></span>\n");
      out.write("                                <span id=\"name\">Sajith Wickramasinghe</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"total-votes\">\n");
      out.write("                            <strong>Total Votes:</strong> <span> 1000456 </span>\n");
      out.write("                        </div>\n");
      out.write("                        <button class=\"Analytics\">See More Analytics</button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"weeklySurvey post votelist reactable province\">\n");
      out.write("                        <div class=\"post-head small-title\">\n");
      out.write("                            <div class=\"post-title\">\n");
      out.write("                                weekly survey 1 - Who will be the next president of Sri Lanka?\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"survey-title\">\n");
      out.write("                            Provincial vote distribution as a percentage of the total\n");
      out.write("                        </div>\n");
      out.write("                        <div id=\"top_x_div\" class=\"chart\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"../script.js\"></script>\n");
      out.write("<script src=\"./surv-pop.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /index/header/header.jsp(19,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("http://localhost:8080/Parlimate/GetPostListServlet");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /index/header/header.jsp(20,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/assets/images/logo.png");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager());
    return false;
  }
}
