/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2025-01-31 12:30:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Profile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDateTime;

public final class postsDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:escapeXml", org.apache.taglibs.standard.functions.Functions.class, "escapeXml", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1725271156711L));
    _jspx_dependants.put("/index/sidebar.jsp", Long.valueOf(1738291084037L));
    _jspx_dependants.put("jar:file:/E:/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/index/header/header.jsp", Long.valueOf(1738291078541L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.time.LocalDateTime");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("    <meta charset=\"UTF-8\"/>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("    <title>My posts</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../index.css\"/>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../index/sidebar1.css\"/>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../index/header/header.css\"/>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../container.css\"/>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../postDetails.css\"/>\n");
      out.write("    <!-- <link rel=\"stylesheet\"\n");
      out.write("href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\"\n");
      out.write("/> -->\n");
      out.write("\n");
      out.write("    <!-- icons -->\n");
      out.write("    <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            data-purpose=\"Layout StyleSheet\"\n");
      out.write("            title=\"Web Awesome\"\n");
      out.write("            href=\"/css/app-wa-09b459cf485d4b1f3304947240314c05.css?vsn=d\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/all.css\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-duotone-solid.css\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-thin.css\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-solid.css\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-regular.css\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            href=\"https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-light.css\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        /* Popup Modal Styles */\n");
      out.write("        .popup-modal {\n");
      out.write("            display: none;\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background: rgba(0, 0, 0, 0.5);\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .popup {\n");
      out.write("            background-color: white;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            width: 400px;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .popup .close-btn {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 10px;\n");
      out.write("            right: 10px;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .formSection {\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .formSection label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .formSection input, .formSection textarea {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 10px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .popbtns {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .post-btn {\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            background-color: #6a5acd;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .post-btn:hover {\n");
      out.write("            background-color: #5b4ab5;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/sidebar1.css\">\n");
      out.write("\n");
      out.write("<div class=\"sidebar pd-1\">\n");
      out.write("    <div class=\"navs\">\n");
      out.write("        <ul>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-Home\" value=\"http://localhost:8080/Parlimate/GetPostListServlet\" checked/>\n");
      out.write("                <label for=\"nav-Home\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-house\"></i>Home</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-announcements\" value=\"http://localhost:8080/Parlimate/Announcements/GetListServlet?announcementId=123\" />\n");
      out.write("                <label for=\"nav-announcements\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-bullhorn\"></i>Announcements</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-fundraise\" value=\"http://localhost:8080/Parlimate/Fundraising/fundraising.jsp\" />\n");
      out.write("                <label for=\"nav-fundraise\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-coins\"></i>Fundraises</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-noti\" value=\"http://localhost:8080/Parlimate/Notification/notification.jsp\" />\n");
      out.write("                <label for=\"nav-noti\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-scale-balanced\"></i>Search & Compare</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-survey\" value=\"http://localhost:8080/Parlimate/Surveys/surveys.jsp\" />\n");
      out.write("                <label for=\"nav-survey\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-clipboard\"></i>Surveys</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-discusRoom\" value=\"http://localhost:8080/Parlimate/DiscussionRoom/discussion-room.jsp\" />\n");
      out.write("                <label for=\"nav-discusRoom\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-people-group\"></i>Meeting Room</label>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <input type=\"radio\" name=\"nav\" id=\"nav-help\" value=\"http://localhost:8080/Parlimate/Help/help.jsp\" />\n");
      out.write("                <label for=\"nav-help\" onclick=\"navigate(this)\"><i class=\"fa-solid fa-headset\"></i>Help/Support</label>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function navigate(label) {\n");
      out.write("        const inputElement = label.previousElementSibling;\n");
      out.write("\n");
      out.write("        // Redirect to the input's value URL\n");
      out.write("        if (inputElement && inputElement.value) {\n");
      out.write("            window.location.href = inputElement.value;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function highlightCurrentPage() {\n");
      out.write("        const currentURL = window.location.href;\n");
      out.write("\n");
      out.write("        // Get all input elements in the sidebar\n");
      out.write("        const inputs = document.querySelectorAll('.sidebar input[type=\"radio\"]');\n");
      out.write("\n");
      out.write("        inputs.forEach(input => {\n");
      out.write("            // If the input's value matches the current URL, check the radio button\n");
      out.write("            if (input.value === currentURL) {\n");
      out.write("                input.checked = true;  // Check the radio input\n");
      out.write("                const label = input.nextElementSibling;\n");
      out.write("                if (label) {\n");
      out.write("                    label.classList.add('selected');  // Add the 'selected' class to the label\n");
      out.write("                }\n");
      out.write("            } else {\n");
      out.write("                const label = input.nextElementSibling;\n");
      out.write("                if (label) {\n");
      out.write("                    label.classList.remove('selected');  // Remove 'selected' class from other labels\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // Call the function when the page loads to highlight and check the current page's button\n");
      out.write("    window.onload = highlightCurrentPage;\n");
      out.write("</script>\n");
      out.write('\n');
      out.write("<link rel=\"stylesheet\" href=\"./header.css\">\n");
      out.write("<style>\n");
      out.write("    .header .logo a img {\n");
      out.write("        height: 20px;\n");
      out.write("        transform: translateY(2px);\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"header pd-2\">\n");
      out.write("    <div class=\"start row\">\n");
      out.write("        <div class=\"sidebar-toggle-btn sideMenuBtn btn\">\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-bars\"></i>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"logo\">\n");
      out.write("            <a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("                <img src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" alt=\"ParlimateLogo\">\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"headerSearchBar row\">\n");
      out.write("        <input type=\"search\" name=\"mainSearch\" id=\"headerSearchBar\"\n");
      out.write("               placeholder=\"Search politicians, Political parties....\" />\n");
      out.write("        <label for=\"headerSearchBar\">\n");
      out.write("            <i class=\"fa-solid fa-magnifying-glass\"></i>\n");
      out.write("        </label>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"headerBtns\">\n");
      out.write("        <div class=\"headerBtn\">\n");
      out.write("            <input type=\"checkbox\" name=\"notifi\" id=\"notificationBtn\" />\n");
      out.write("            <label for=\"notificationBtn\" class=\"btn\">\n");
      out.write("                <i class=\"fa-solid fa-bell\"></i>\n");
      out.write("            </label>\n");
      out.write("            <span class=\"tip\">notifications</span>\n");
      out.write("            <div class=\"dropDownMenu\">\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\" class=\"notification\">\n");
      out.write("                            <div class=\"noti-img\"></div>\n");
      out.write("                            <div class=\"noti-title\">\n");
      out.write("                                <div class=\"notification-from\">\n");
      out.write("                                    Ranil wickramasinghe\n");
      out.write("                                </div>\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\n");
      out.write("											consectetur adipisicing elit. Qui,\n");
      out.write("											ullam. Quos aperiam in re</span>\n");
      out.write("                            </div>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\" class=\"notification\">\n");
      out.write("                            <div class=\"noti-img\"></div>\n");
      out.write("                            <div class=\"noti-title\">\n");
      out.write("                                <div class=\"notification-from\">\n");
      out.write("                                    Ranil wickramasinghe\n");
      out.write("                                </div>\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\n");
      out.write("											consectetur adipisicing elit. Qui,\n");
      out.write("											ullam. Quos aperiam in re</span>\n");
      out.write("                            </div>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\" class=\"notification\">\n");
      out.write("                            <div class=\"noti-img\"></div>\n");
      out.write("                            <div class=\"noti-title\">\n");
      out.write("                                <div class=\"notification-from\">\n");
      out.write("                                    Ranil wickramasinghe\n");
      out.write("                                </div>\n");
      out.write("                                <span>Lorem, ipsum dolor sit amet\n");
      out.write("											consectetur adipisicing elit. Qui,\n");
      out.write("											ullam. Quos aperiam in re</span>\n");
      out.write("                            </div>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <a href=\"./Announcements/announcements.html\" class=\"bottom-btn small-text capitalize\">\n");
      out.write("                    see all notifications\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"headerBtn\">\n");
      out.write("            <input type=\"checkbox\" name=\"profile\" id=\"profileBtn\" />\n");
      out.write("            <label for=\"profileBtn\" class=\"btn\">\n");
      out.write("                <i class=\"fa-solid fa-user\"></i>\n");
      out.write("            </label>\n");
      out.write("            <span class=\"tip\">profile</span>\n");
      out.write("            <div class=\"dropDownMenu\">\n");
      out.write("                <div class=\"profile\">\n");
      out.write("                    <a href=\"http://localhost:8080/Parlimate/Profile/profile.jsp\">\n");
      out.write("                        <div class=\"img\"></div>\n");
      out.write("                        <div class=\"details\">\n");
      out.write("                            <div class=\"name medium-text bold\">\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfile.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"email small-text\">\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("                <ul class=\"capitalize\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("									<span>\n");
      out.write("										<i class=\"fa-regular fa-gear\"></i>\n");
      out.write("									</span>\n");
      out.write("                            <span> account settings </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <div class=\"sep-line\"></div>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("									<span>\n");
      out.write("										<i class=\"fa-regular fa-circle-question\"></i>\n");
      out.write("									</span>\n");
      out.write("                            <span> help center </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("									<span>\n");
      out.write("										<i class=\"fa-regular fa-star\"></i>\n");
      out.write("									</span>\n");
      out.write("                            <span> upgrade plan </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <div class=\"sep-line\"></div>\n");
      out.write("\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"logoutBtn capitalize\">\n");
      out.write("                            <div class=\"cont\">\n");
      out.write("                                <input type=\"checkbox\" name=\"logoutBtn\" id=\"logoutBtn\" />\n");
      out.write("                                <label for=\"logoutBtn\">\n");
      out.write("                                    <i class=\"fa-solid fa-sign-out\"></i>\n");
      out.write("                                    <span>logout</span>\n");
      out.write("                                </label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <div class=\"pageTitles\">\n");
      out.write("        <h2 class=\"title\">My posts</h2>\n");
      out.write("        <div class=\"subTitle\">Political activities and Discussions</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"search\">\n");
      out.write("        <label for=\"searchInput\" class=\"icon\">\n");
      out.write("            <i class=\"fa-solid fa-magnifying-glass\"></i>\n");
      out.write("        </label>\n");
      out.write("        <input type=\"text\" id=\"searchInput\" placeholder=\"Search posts...\" onkeyup=\"filterAnnouncements()\">\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"post-list\">\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Update Announcement Popup Modal -->\n");
      out.write("<div class=\"popup-modal\" id=\"editPopup\">\n");
      out.write("    <div class=\"popup\">\n");
      out.write("        <div class=\"title\">\n");
      out.write("            <span>Edit Post</span>\n");
      out.write("            <button class=\"close-btn\" onclick=\"closeEditPopup()\">\n");
      out.write("                <i class=\"fa-solid fa-times\"></i>\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form action=\"UpdatePostServlet\" method=\"post\">\n");
      out.write("            <!-- Hidden fields for post ID and user ID -->\n");
      out.write("            <input type=\"hidden\" name=\"postid\" id=\"postid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${postid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("            <input type=\"hidden\" name=\"userid\" id=\"userid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("\n");
      out.write("            <!-- Content Section -->\n");
      out.write("            <div class=\"formSection\">\n");
      out.write("                <label for=\"editContent\">Content</label>\n");
      out.write("                <textarea id=\"editContent\" name=\"content\" placeholder=\"Edit content here...\" required></textarea>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Save Button -->\n");
      out.write("            <div class=\"popbtns\">\n");
      out.write("                <button type=\"submit\" class=\"post-btn\">Save Changes</button>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    let sideMenuBtns = document.querySelectorAll(\".sideMenuBtn\");\n");
      out.write("    const body = document.querySelector(\"body\");\n");
      out.write("    const navRadios = document.querySelectorAll('input[name=\"nav\"]');\n");
      out.write("\n");
      out.write("    sideMenuBtns.forEach((btn) => {\n");
      out.write("        btn.addEventListener(\"click\", () => {\n");
      out.write("            if (body.classList.contains(\"sidebar-deactive\")) {\n");
      out.write("                body.classList.remove(\"sidebar-deactive\");\n");
      out.write("            } else {\n");
      out.write("                body.classList.add(\"sidebar-deactive\");\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    navRadios.forEach(radio => {\n");
      out.write("        radio.addEventListener('change', (event) => {\n");
      out.write("            const selectedValue = event.target.value;\n");
      out.write("            if (selectedValue) {\n");
      out.write("                window.location.href = selectedValue; // Redirect to the selected page\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // Function to open the modal and populate the form\n");
      out.write("    function openEditPopup(postid, userid, content, datetime) {\n");
      out.write("        // Show the popup modal\n");
      out.write("        document.getElementById('editPopup').style.display = 'flex';\n");
      out.write("\n");
      out.write("        // Remove milliseconds from the datetime value\n");
      out.write("        const formattedDatetime = datetime.substring(0, 16);\n");
      out.write("\n");
      out.write("        // Populate the form with the current announcement data\n");
      out.write("        document.getElementById('postid').value = postid;\n");
      out.write("        document.getElementById('userid').value = userid;\n");
      out.write("\n");
      out.write("        document.getElementById('editContent').value = content;\n");
      out.write("        document.getElementById('editDatetime').value = formattedDatetime;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // Function to close the popup modal\n");
      out.write("    function closeEditPopup() {\n");
      out.write("        // Hide the popup modal\n");
      out.write("        document.getElementById('editPopup').style.display = 'none';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // Function to filter announcements\n");
      out.write("    function filterAnnouncements() {\n");
      out.write("        const input = document.getElementById(\"searchInput\").value.toUpperCase();\n");
      out.write("        const listItems = document.querySelectorAll(\".announcement-item\");\n");
      out.write("\n");
      out.write("        listItems.forEach(item => {\n");
      out.write("            const text = item.textContent || item.innerText;\n");
      out.write("            item.style.display = text.toUpperCase().includes(input) ? \"\" : \"none\";\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script src=\"../script.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /index/header/header.jsp(19,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("http://localhost:8080/Parlimate/GetPostListServlet");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /index/header/header.jsp(20,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/assets/images/logo.png");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /Profile/postsDetail.jsp(141,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("post");
    // /Profile/postsDetail.jsp(141,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Profile/postsDetail.jsp(141,8) '${allposts}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${allposts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <li class=\"post-item post reactable\">\n");
          out.write("                <div class=\"post-header row\">\n");
          out.write("                    <div class=\"pro-img\"></div>\n");
          out.write("                    <div class=\"posted-by col\">\n");
          out.write("                        <p class=\"pName\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("                        <p class=\"pDate\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.datetime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("                    </div>\n");
          out.write("                </div>\n");
          out.write("                <div class=\"post-content\">\n");
          out.write("                    <div class=\"seperator sepT\"></div>\n");
          out.write("                        ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("                </div>\n");
          out.write("                <div class=\"post-actions\">\n");
          out.write("                    <!-- Update Button triggers the popup modal with announcement data -->\n");
          out.write("                    <button class=\"button button-update\"\n");
          out.write("                            onclick=\"openEditPopup('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.postId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("',  '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:escapeXml(post.content)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.datetime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">\n");
          out.write("                        Update\n");
          out.write("                    </button>\n");
          out.write("\n");
          out.write("\n");
          out.write("                    <!-- Delete Button -->\n");
          out.write("                    <form action=\"DeletePostServlet\" method=\"post\"\n");
          out.write("                          onsubmit=\"return confirm('Are you sure you want to delete this post?');\"\n");
          out.write("                          style=\"display:inline;\">\n");
          out.write("                        <input type=\"hidden\" name=\"postid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.postId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("                        <button type=\"submit\" class=\"button button-delete\">Delete</button>\n");
          out.write("                    </form>\n");
          out.write("\n");
          out.write("\n");
          out.write("                </div>\n");
          out.write("                <div class=\"reactions\">\n");
          out.write("                    <button class=\"like btn\">\n");
          out.write("					<span class=\"reactIcon\">\n");
          out.write("						<i class=\"fa-solid fa-thumbs-up\"></i>\n");
          out.write("					</span>\n");
          out.write("                        <span>like</span>\n");
          out.write("                        <span class=\"count\"> 32k </span>\n");
          out.write("                    </button>\n");
          out.write("                    <button class=\"comment btn\">\n");
          out.write("					<span class=\"reactIcon\">\n");
          out.write("						<i class=\"fa-solid fa-message\"></i>\n");
          out.write("					</span>\n");
          out.write("                        <span>comment</span>\n");
          out.write("                        <span class=\"count\">1k</span>\n");
          out.write("                    </button>\n");
          out.write("                    <button class=\"share btn\">\n");
          out.write("					<span class=\"reactIcon\">\n");
          out.write("						<i class=\"fa-duotone fa-solid fa-share-all\"></i>\n");
          out.write("					</span>\n");
          out.write("                        <span>share</span>\n");
          out.write("                    </button>\n");
          out.write("                </div>\n");
          out.write("            </li>\n");
          out.write("            &nbsp;&nbsp;\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager());
    return false;
  }
}
